- hosts: masters
  become: yes
  # vars_prompt:
  #   - name: git_user
  #     private: no
  #   - name: git_pass
  #     private: yes
  tasks:
    - name: (IP Pool - Load Balancer) install MetalLB 
      become: yes
      become_user: kube
      shell: kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/metallb-installation.yaml 
      args:
        chdir: $HOME
    - name: Clone App Env form github
      ansible.builtin.git:
        repo: https://github.com/northboys/App-env.git
        dest: /src/App-env/
        single_branch: yes
        version: main
    - name: Add the istioctl client to your path
      args:
        chdir: "/src/App-env/istio-1.11.1"
      shell: mv bin/istioctl /usr/local/bin/

    - name: (Ingress & Service Mesh) install Istio Mesh
      become: yes
      become_user: kube
      shell: istioctl install --set profile=demo -y  
      args:
        chdir: "/src/App-env/istio-1.11.1"

    - name: install Istio Telemetry Addons
      become: yes
      become_user: kube
      shell: |
               kubectl apply -f samples/addons
               kubectl rollout status deployment/kiali -n istio-system
      args:
        chdir: "/src/App-env/istio-1.11.1"
    - name: (Certificate Management) install Cert-Manager 
      become: yes
      become_user: kube
      shell: kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/cert-manager-v1.5.3.yaml
      args:
        chdir: $HOME
    - name: (Certificate Management) install Cluster Issuer 
      become: yes
      become_user: kube
      shell: kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/cluster-issuer.yaml
      args:
        chdir: $HOME
    - name: (Certificate Management) install Cert for public domain
      become: yes
      become_user: kube
      shell: |
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/certificate-gitlab.yaml
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/certificate-enggano.yaml
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/certificate-grafana.yaml
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/certificate-kiali.yaml
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/certificate-longhorn.yaml
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/certificate-nexus.yaml
      args:
        chdir: $HOME
    - name: (Storage) install Longhorn ISCSI
      become: yes
      become_user: kube
      shell: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.2.0/deploy/prerequisite/longhorn-iscsi-installation.yaml
      args:
        chdir: $HOME
    - name: (Storage) install Longhorn
      become: yes
      become_user: kube
      shell: |
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/longhorn-installation.yaml
               kubectl apply -f https://raw.githubusercontent.com/northboys/App-env/main/longhorn-istio-installation.yaml
      args:
        chdir: $HOME
    # setup end <need testing>
    
    # - name: (Container Registry) install NexusOSS
    #   become: yes
    #   become_user: kube
    #   shell: | 
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/nexus-installation.yaml
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/nexus-istio-installation.yaml
    #   args:
    #     chdir: $HOME
    # - name: (Application Repository) install Gitlab
    #   become: yes
    #   become_user: kube
    #   shell: |
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/gitlab-installation.yaml
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/gitlab-istio-installation.yaml 
    #   args:
    #     chdir: $HOME

    # - name: (Enggano Environment) install Mysql-Moco
    #   become: yes
    #   become_user: kube
    #   shell: |
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/moco-operator-installation.yaml
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/moco-mysql-volume.yaml 
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/moco-mysql-pvc.yaml
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/moco-mysql-cluster.yaml
    #   args:
    #     chdir: $HOME
    # - name: (Enggano Environment) install Redis
    #   become: yes
    #   become_user: kube
    #   shell: |
    #            kubectl apply -f https://keepo.mit.id/izalul/enggano-environment/raw/master/redis-installation.yaml
    #   args:
    #     chdir: $HOME
    
    # - name: (Enggano Environment) install Enggano-Core
    #   become: yes
    #   become_user: kube
    #   shell: kubectl apply -f <file.yaml URL>  
    #   args:
    #     chdir: $HOME
    # - name: (Enggano Environment) install Enggano-Ingress
    #   become: yes
    #   become_user: kube
    #   shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
    #   args:
    #     chdir: $HOME
 
