- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
   - name: Copy join command from Ansiblehost to the worker nodes.
     become: yes
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command
     register: joined_or_not
   
   - name: Add systemd flag to kubelet conf
     blockinfile:
       path: "/var/lib/kubelet/kubeadm-flags.env"
       block: |
             KUBELET_KUBEADM_ARGS="--container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint=/var/run/crio/crio.sock"

   - name: reload systemd and restart kubelet service
     shell: |
              systemctl daemon-reload
              systemctl restart kubelet
